# [server] 今回はstreamlitで実施する、その際のポート番号は8501らしいから
# headless = true
# address = "0.0.0.0"
# port = 5000

[theme]
# Atom One Dark inspired theme
primaryColor = "#61AFEF"
backgroundColor = "#282C34"
secondaryBackgroundColor = "#3E4451"
textColor = "#ABB2BF"
font = "sans serif"
